default_language_version:
    python: python
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.1.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args:
          # making isort line length compatible with black
          - "--max-line-length=110"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,W504,F403,F401,E402"
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: # arguments to configure black
          - --line-length=110
          - --include='\.pyi?$'
          # these folders wont be formatted by black
          - --exclude="""\.git |
              \.__pycache__|
              \.hg|
              \.mypy_cache|
              \.tox|
              \.venv|
              _build|
              buck-out|
              build|
              dist"""
